### PR TITLE
Multi monitor support

### PR DESCRIPTION
**Pull request by ocaballeror**
I know it's a quick fix, but I got multi monitor working with this. It's just a for loop to replicate the bar on all the displays, with their respective offset

### CODE REVIEW

**Comment by ocaballeror** [comment]
The above was a really clunky fix, it created multiple bars and put one in each monitor instead of showing the same one on all of them. This led to information updating on one bar but not the others, which can look pretty confusing some times.

The correct way, if anyone is interested, would be to change the last part of i3_lemonbar_parser.sh from
```sh
# And finally, output
printf "%s\n" "%{l}${wsp}${title} %{r}${mpd}${stab}${irc}${stab}${gmail}${stab}${cpu}${stab}${mem}${stab}${diskr}${stab}${diskh}${stab}${wland}${stab}${wlanu}${stab}${ethd}${stab}${ethu}${stab}${vol}${stab}${date}${stab}${time}"
```

To
```sh
bar="$(printf '%s\n' "%{l}${wsp}${title} %{r}${mpd}${stab}${irc}${stab}${gmail}${stab}${cpu}${stab}${mem}${stab}${diskr}${stab}${diskh}${stab}${wland}${stab}${wlanu}${stab}${ethd}${stab}${ethu}${stab}${vol}${stab}${date}${stab}${time}")"

out=""
mcount="$(xrandr --listactivemonitors | head -1 | awk '{print $2}')"
for i in $(seq 0 $((mcount -1))); do
	out+="%{S$i}$bar"
done
echo "$out"
```

I have been using the latter solution for a while and had no issues with it.

**Comment by electro7** [comment]
Thanks a lot! I only have one monitor. 

I try to check this path and include in my settings.

**Comment by leifmadsen** [comment]
Just threw this into my own local configuration, and it seems to work fine :)

My offsets seem to be reversed, but at least now I don't have the 2, 3, 1 setup that I had before!

**Comment by ocaballeror** [comment]
Just for reference, I found out that 
```sh
mcount="$(xrandr | grep -wo connected | wc -l)"
```

is a better solution than 

```sh
mcount="$(xrandr --listactivemonitors | head -1 | awk '{print $2}')"
```

since --listactivemonitors is a relatively new option in xrandr and some distros may not support it (looking at you, Debian)

**Pull request closed without merging**
